[build]
  command = "npm install && npm run build"
  functions = ".netlify/functions"
  publish = ".next"
  base = "."

[build.environment]
  NODE_VERSION = "18"
  # Supabase Configuration
  NEXT_PUBLIC_SUPABASE_URL = "https://diubdforaeqzbtbwxdfc.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpdWJkZm9yYWVxemJ0Ynd4ZGZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NDc4NDUsImV4cCI6MjA3MDMyMzg0NX0.W9kNfkg3HE_fjIWlCggY2qcButBKUvBCsNQ8955CY1I"
  # NextAuth Configuration  
  NEXTAUTH_SECRET = "NkX2i6xxAw0eZkWIQEG8h05y7g3c1QYFflAowawmQ6E="
  NEXTAUTH_URL = "https://1cube.netlify.app"
  # Application Configuration
  BASE_URL = "https://1cube.netlify.app"
  # Shopee API Configuration
  SHOPEE_PARTNER_ID = "1181853"  
  SHOPEE_PARTNER_KEY = "shpk4862574b726c77774655794f5241555a534d447876475678795048577a61"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production]
  command = "npm run build"

[context.deploy-preview]
  command = "npm run build"

[context.branch-deploy]
  command = "npm run build"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Redirects for SPA routing
[[redirects]]
  from = "/app/*"
  to = "/app/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
